### ISSUE TITLE
Error in 6.3: Unable to initialize JCR_OAK resource resolver factory

### ISSUE THREAD

**Issue by parveendudy** [icfnext/prosper#22]
**After we upgraded to AEM 6.3.3.2 and updated Prosper version to 14.0.0 (as recommended), we are getting following error in our unit test cases which were earlier working fine in AEM 6.2/Prosper 11.0.0**

`java.lang.RuntimeException: Unable to initialize JCR_OAK resource resolver factory: Unable to invoke method 'activate' for class org.apache.sling.testing.mock.sling.oak.OakMockSlingRepository
	at org.apache.sling.testing.mock.sling.context.ContextResourceResolverFactory.get(ContextResourceResolverFactory.java:66)
	at org.apache.sling.testing.mock.sling.context.SlingContextImpl.newResourceResolverFactory(SlingContextImpl.java:125)
	at org.apache.sling.testing.mock.sling.context.SlingContextImpl.resourceResolverFactory(SlingContextImpl.java:130)
	at org.apache.sling.testing.mock.sling.context.SlingContextImpl.setUp(SlingContextImpl.java:114)
	at org.apache.sling.testing.mock.sling.junit.SlingContext.access$100(SlingContext.java:40)
	at org.apache.sling.testing.mock.sling.junit.SlingContext$1.before(SlingContext.java:127)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:39)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.RuntimeException: Unable to invoke method 'activate' for class org.apache.sling.testing.mock.sling.oak.OakMockSlingRepository
	at org.apache.sling.testing.mock.osgi.OsgiServiceUtil.invokeMethod(OsgiServiceUtil.java:320)
	at org.apache.sling.testing.mock.osgi.OsgiServiceUtil.invokeLifecycleMethod(OsgiServiceUtil.java:149)
	at org.apache.sling.testing.mock.osgi.OsgiServiceUtil.activateDeactivate(OsgiServiceUtil.java:84)
	at org.apache.sling.testing.mock.osgi.MockOsgi.activate(MockOsgi.java:171)
	at org.apache.sling.testing.mock.sling.ResourceResolverFactoryInitializer.registerServiceIfNotPresent(ResourceResolverFactoryInitializer.java:165)
	at org.apache.sling.testing.mock.sling.ResourceResolverFactoryInitializer.registerServiceIfNotPresent(ResourceResolverFactoryInitializer.java:150)
	at org.apache.sling.testing.mock.sling.ResourceResolverFactoryInitializer.setUp(ResourceResolverFactoryInitializer.java:61)
	at org.apache.sling.testing.mock.sling.MockSling.newResourceResolverFactory(MockSling.java:75)
	at org.apache.sling.testing.mock.sling.context.ContextResourceResolverFactory.get(ContextResourceResolverFactory.java:45)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: org/apache/jackrabbit/oak/plugins/document/bundlor/BundlingConfigInitializer
	at org.apache.jackrabbit.oak.plugins.nodetype.write.InitialContent.initialize(InitialContent.java:88)
	at org.apache.jackrabbit.oak.plugins.nodetype.write.InitialContent.createInitialContent(InitialContent.java:61)
	at org.apache.jackrabbit.oak.plugins.nodetype.write.InitialContent.<clinit>(InitialContent.java:57)
	at org.apache.jackrabbit.oak.jcr.Jcr.<init>(Jcr.java:114)
	at org.apache.jackrabbit.oak.jcr.Jcr.<init>(Jcr.java:141)
	at org.apache.sling.testing.mock.sling.oak.OakMockSlingRepository.activate(OakMockSlingRepository.java:73)
	at org.apache.sling.testing.mock.osgi.OsgiServiceUtil.invokeMethod(OsgiServiceUtil.java:311)
	... 24 more
Caused by: java.lang.ClassNotFoundException: org.apache.jackrabbit.oak.plugins.document.bundlor.BundlingConfigInitializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more`

**Comment by lykorian** [comment]
Can you attach the `dependencies` section of your pom.xml file that includes Prosper?  Typically these type of errors are caused by conflicts in the dependency versions between your project and the Sling testing tools.

**Comment by parveendudy** [comment]
see below

	<dependencies>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.jcr</groupId>
			<artifactId>jcr</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.cmpn</artifactId>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.scr.annotations</artifactId>
			<version>1.12.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-exec</artifactId>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.icfolson.aem.library</groupId>
			<artifactId>aem-library-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.icfolson.aem.library</groupId>
			<artifactId>aem-library-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.icfolson.aem.library</groupId>
			<artifactId>aem-library-models</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.citytechinc.cq.cq-component-plugin</groupId>
			<artifactId>cq-component-annotations</artifactId>
			<version>${component.plugin.version}</version>
		</dependency>
		<dependency>
			<groupId>com.citytechinc.cq.cq-component-plugin</groupId>
			<artifactId>cq-component-maven-plugin</artifactId>
			<version>${component.plugin.version}</version>
		</dependency>
		<dependency>
			<groupId>com.icfolson.aem</groupId>
			<artifactId>multicomposite-addon</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>org.springframework.web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.amqp</groupId>
			<artifactId>spring-rabbit</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient-osgi</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore-osgi</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.apache.sling</groupId>
			<artifactId>org.apache.sling.hc.core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.sling</groupId>
			<artifactId>org.apache.sling.hc.annotations</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.8.2</version>
		</dependency>

		
		<dependency>
			<groupId>com.mathworks.internal.foundation</groupId>
			<artifactId>namedresource</artifactId>
		</dependency>
		<dependency>
			<groupId>com.mathworks.internal.core</groupId>
			<artifactId>healthmonitor</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.drools</groupId>
			<artifactId>drools-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.drools</groupId>
			<artifactId>drools-compiler</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jdt.core.compiler</groupId>
			<artifactId>ecj</artifactId>
			<version>4.4.2</version>
			<systemPath>${basedir}/../local_jars/ecj-4.4.2-fixed.jar</systemPath>
			<scope>system</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>
		<dependency>
			<groupId>org.codehaus.woodstox</groupId>
			<artifactId>woodstox-core-asl</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-email</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.cocoon</groupId>
			<artifactId>cocoon-xml</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
		</dependency>
		<dependency>
			<groupId>com.day.cq</groupId>
			<artifactId>cq-replication</artifactId>
			<version>5.4.24</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.adobe.granite</groupId>
			<artifactId>com.adobe.granite.poi</artifactId>
			<version>2.0.22</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>15.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>3.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.icfolson.aem.prosper</groupId>
			<artifactId>prosper</artifactId>
			<version>14.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.day.cq.wcm</groupId>
			<artifactId>cq-wcm-core</artifactId>
		</dependency>
	</dependencies>
